name: Build and Release RPM

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            container: registry.fedoraproject.org/fedora:42
            rpm_arch: x86_64
            env:
              CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
          - arch: aarch64
            container: registry.fedoraproject.org/fedora:42
            rpm_arch: aarch64
            env:
              CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu


    container:
      image: ${{ matrix.container }}

    env:
      CARGO_BUILD_TARGET: ${{ matrix.env.CARGO_BUILD_TARGET }}

    steps:
      - name: Install build dependencies
        run: |
          dnf -y update
          dnf -y install rpmdevtools gcc rustup ca-certificates kernel-headers
          rustup-init -y --target $CARGO_BUILD_TARGET
          . "$HOME/.cargo/env"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare RPM build environment
        run: |
          rpmdev-setuptree
          cp uutils-coreutils/*.spec ~/rpmbuild/SPECS/
          spectool -C ~/rpmbuild/SOURCES/ -g ~/rpmbuild/SPECS/uutils-coreutils.spec

      - name: Build RPM
        run: |
          . "$HOME/.cargo/env"
          rpmbuild -ba ~/rpmbuild/SPECS/*.spec --target ${{ matrix.rpm_arch }}

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS -name "*.rpm" | grep -v debuginfo | head -n 1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: uutils-coreutils-${{ matrix.arch }}
          path: ${{ steps.find_rpm.outputs.rpm_path }}

  release:
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.rpm
