name: Build and Release RPM for x86_64

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-rpm:
    runs-on: fedora-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name:
        run: |
          dnf -y update
          dnf -y install rpmdevtools gcc rust cargo ca-certificates kernel-headers
          rpmdev-setuptree
          cp uutils-coreutils/*.spec ~/rpmbuild/SPECS/
          spectool -C ~/rpmbuild/SOURCES/ -g ~/rpmbuild/SPECS/uutils-coreutils.spec
          rpmbuild -ba ~/rpmbuild/SPECS/*.spec
          RPM_PATH=$(find ~/rpmbuild/RPMS -name "*.rpm" | grep -v debuginfo | head -n 1)
          mkdir -p /github/workspace/artifacts
          cp "$RPM_PATH" /github/workspace/artifacts/

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: uutils-coreutils-${{ matrix.arch }}
          path: artifacts/*.rpm

  release:
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.rpm
